services:
  api:
    container_name: eezy_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 4041:4041
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DB_NAME: eezyApp
      DB_USER: eezy_usr
      DB_PASSWORD: eezyRoot
      DB_HOST: mysql
      DB_ENGINE: mariadb
    networks:
      - eezy_net

  client:
    image: nginx:latest
    working_dir: /srv/www/app
    ports:
      - 8080:80
    # environment: # NEEDED?
    #   - NGINX_HOST=eezyHost
    #   - NGINX_PORT=80
    volumes:
    # DEFAULT NGINX SERVE DIR
    - ./src/client/dist/:/usr/share/nginx/html/
    # IF NGINX CONF IS NEEDED
    #   - ./src/client/cfg/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mariadb:latest
    container_name: mysql-eezy
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - eezy_db:/var/lib/mysql
      - ./cfg/srv/mysql/init.sql:/data/application/init.sql
      # https://stackoverflow.com/questions/71443028/building-mysql-mariadb-database-with-scema-in-docker
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: eezyApp
      MARIADB_USER: eezy_usr
      MARIADB_PASSWORD: eezyRoot
    networks:
      - eezy_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MARIADB_ROOT_PASSWORD: root
    networks:
      - eezy_net

volumes:
  eezy_db:
networks:
  eezy_net:
