services:
  api:
    container_name: eezy_api
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      DB_NAME: eezyApp
      DB_USER: eezy_usr
      DB_PASSWORD: eezyRoot
      DB_HOST: mysql
      DB_ENGINE: mariadb
    networks:
      - eezy_net

#   client:
#     image: nginx:latest
#     working_dir: /srv/www/app
#     ports:
#       - 8080:80
#     # environment: # NEEDED?
#     #   - NGINX_HOST=eezyHost
#     #   - NGINX_PORT=80
#     volumes:
#     # DEFAULT NGINX SERVE DIR
#     - ./src/client/dist/:/usr/share/nginx/html/
#     # IF NGINX CONF IS NEEDED
#     #   - ./src/client/cfg/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     restart: always

  mysql:
    image: mariadb:latest
    volumes:
      - eezy_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eezyApp
      MYSQL_USER: eezy_usr
      MYSQL_PASSWORD: eezyRoot
    networks:
      - eezy_net

volumes:
  eezy_db:
networks:
  eezy_net: