services:
  api:
    image: node:20-alpine
    build:
      context: ./src/api
      dockerfile: Dockerfile
    command: sh -c "yarn && yarn run start"
    ports:
      - 4001:4001
    working_dir: /app
    volumes:
      - ./src/api:/app
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_USER: eezy
      MYSQL_PASSWORD: eezyPassword
      MYSQL_DB: eezyApp

  client:
    image: nginx:latest
    working_dir: /srv/www/app
    ports:
      - 8080:80
    # environment:
    #   - NGINX_HOST=eezyHost
    #   - NGINX_PORT=80
    volumes:
    #   - ./src/client/dist:/srv/www/app
      - ./src/client/dist/:/usr/share/nginx/html/
    #   - ./src/client/cfg/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mysql:
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: eezy_usr
      MYSQL_PASSWORD: eezy_Password
      MYSQL_DATABASE: eezyApp

volumes:
  mysql:
