services:
  api:
    image: node:20-alpine
    build:
      context: ./src/api
      dockerfile: Dockerfile
    command: sh -c "yarn && yarn run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./src/api:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: eezy
      MYSQL_PASSWORD: eezyPassword
      MYSQL_DB: eezyApp

  client:
    image: node:20-alpine
    command: sh -c "yarn && yarn run start"
    working_dir: /app
    volumes:
      - ./src/client:/app

  mysql:
    image: mariadb:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: eezy
      MYSQL_PASSWORD: eezyPassword
      MYSQL_DATABASE: eezyApp

volumes:
  mysql:
